name: "makephile"

services:
  makephile:
    image: empaphy/makephile:${MAKEPHILE_VERSION:-1.x}
    build: .
    volumes:
      - { type: bind, source: ., target: /opt/makephile, bind: { create_host_path: true } }
